name: Clang Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "mscl*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [9, 10, 11]
        build_type: [Debug, Release]
        os: [ubuntu-18.04]
    container:
      image: conanio/clang${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install --upgrade conan
      - name: Configure Conan
        run: conan remote add sintef ${CONAN_UPLOAD}
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -b missing -b outdated --update . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
